openapi: 3.0.1
info:
  title: Certificate Template API
  description: These apis are used to create, update and fetch certificate templates.
              - [TestCases](https://app.getpostman.com/run-collection/9d9053de65748c341609)
  version: "1.0"
servers:
- url: https://staging.open-sunbird.org/api
paths:
  /cert/v1/template/create:
    post:
      tags:
      - Certificate Template API
      summary: Create certificate template
      description: |-
        This API creates the certificate templates.
           - The **_ /template/create_** endpoint creates a certificate template in the system.
           - All fields marked with an * are mandatory
           - Required fields cannot be null or empty
           - Accepts certificate template name , template , description etc
           - Backend Route: http://cert-service:9000/cert/v1/template/create
      operationId: CreateCertificateTemplate
      parameters:
      - name: Content-Type
        in: header
        description: The content type entity is the media type of the resource. Possible
          media types can be Application/json
        required: true
        schema:
          type: string
      requestBody:
        description: The body refers to the format of the request. The body contains
          metadata about the request to add the certificate template.
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ApiRequest'
              - $ref: '#/components/schemas/AddCertificateTemplateRequest'
            examples:
             a:
              summary: Template Create Request
              value:
                request:
                  certificate:
                    template:
                      identifier: template_01_pdf_stag
                      name: Course completion pdf certificate staging
                      template: https://sunbirddev.blob.core.windows.net/sunbird-content-dev/content/test_template_stag/artifact/cbse-certificate.zip
                      params:
                      - issuer.name
                      - issuer.url
             b:
              summary: Mandatory Param Missing Request
              value:
                request:
                  certificate:
                    template:
                      identifier: template_01_pdf_stag
                      params:
                      - issuer.name
                      - issuer.url
        required: true
      responses:
        200:
          description: OK ! Operation successful. The **Create certificate template**
            operation was executed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ApiResponse:
                    $ref: '#/components/schemas/ApiResponse'
                  SuccessResponse:
                    $ref: '#/components/schemas/SuccessResponse'
              example:
                id: 
                ver: 
                ts: 
                params: 
                responseCode: OK
                result:
                  identifier: templateId
        400:
          description: BAD REQUEST. The "Create certificate template" operation failed.
            Input for a mandatory parameter may be missing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddCertificateTemplateErrorResponse'
              examples:
                a: 
                 summary: Mandatory Param Missing Response
                 value:
                  id: cert.v1.template.create
                  ver: v1
                  ts: 1606719505532
                  responseCode: CLIENT_ERROR
                  result:
                    message: Request is empty.
                b: 
                 summary: Mandatory Param Name Missing Response
                 value:
                  id: cert.v1.template.create
                  ver: v1
                  ts: 1606719505532
                  responseCode: CLIENT_ERROR
                  result:
                    message: name or template missing in request.
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong. These
            errors are tracked automatically. Try refreshing the page. If the problem
            persists, contact info@sunbird.org.
          content: 
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/500ServerError'
              example:
                id: cert.v1.template.create
                ver: v1
                ts: 1601451354559
                params: 
                  msgid: "string"
                  status: "string"
                  resmsgid: string
                responseCode: SERVER_ERROR
                result:
                  message: Process failed,please try again later.
      security:
      - bearer: []

  /cert/v1/template/update/{templateId}:
    patch:
      tags:
      - Certificate Template API
      summary: update the certificate template
      description: |-
        This API updates the certificate templates.
           - The **_ /template/update_** endpoint updates the certificate template.
           - All fields marked with an * are mandatory
           - Required fields cannot be null or empty
           - Backend Route: http://cert-service:9000/cert/v1/template/update/:templateId
           
      operationId: UpdateCertificateTemplate
      parameters:
      - name: templateId
        in: path
        description: Append a valid template ID To the Request URL
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: The Content Type entity is the media type of the resource.Possible
          media types can be Application/json
        required: true
        schema:
          type: string
      requestBody:
        description: The body refers to the format of the request. The body contains
          metadata about the request to update the certificate template.
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ApiRequest'
              - $ref: '#/components/schemas/UpdateCertificateTemplateRequest'
            example:
              request:
                certificate:
                  template:
                    name: Course completion pdf certificate staging
                    template: https://sunbirddev.blob.core.windows.net/sunbird-content-dev/content/test_template_stag/artifact/cbse-certificate.zip
                    params:
                    - issuer.name
                    - issuer.url
        required: true
      responses:
        200:
          description: OK ! Operation successful."Update Certificate template" operation
            was executed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ApiResponse:
                    $ref: '#/components/schemas/ApiResponse'
                  SuccessResponse:
                    $ref: '#/components/schemas/SuccessResponse'
              example:
                id: 
                ver: 
                ts: 
                params: 
                responseCode: OK
                result:
                  identifier: template_01_pdf_stag
        400:
          description: BAD REQUEST. The "Update Certificate template" operation failed.
            Input for a mandatory parameter may be missing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCertificateTemplateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong. These
            errors are tracked automatically. Try refreshing the page. If the problem
            persists, contact info@sunbird.org.
          content: 
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/500ServerError'
              example:
                id: cert.v1.template.update
                ver: v1
                ts: 1601451354559
                params: 
                  msgid: "string"
                  status: "string"
                  resmsgid: string
                responseCode: SERVER_ERROR
                result:
                  message: Process failed,please try again later.
      security:
      - bearer: []

  /cert/v1/template/read/{templateId}:
    get:
      tags:
      - Certificate Template API
      summary: read the certificate template
      description: |-
        This API fetches the certificate templates.
           - The **_ /template/read_** endpoint fetches the certificate template.
           - All fields marked with an * are mandatory
           - Required fields cannot be null or empty
           - Backend Route: http://cert-service:9000/cert/v1/template/read/:templateId
      operationId: GetCertificateTemplate
      parameters:
      - name: templateId
        in: path
        description: Append a valid template ID To the Request URL
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: The Content Type entity is the media type of the resource.Possible
          media types can be Application/json
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK ! Operation successful."Read Certificate template" operation
            was executed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ApiResponse:
                    $ref: '#/components/schemas/ApiResponse'
                  GetCertificateTemplateResponse:
                    $ref: '#/components/schemas/GetCertificateTemplateResponse'
              example:
                id: 
                ver: 
                ts: 
                params: 
                responseCode: OK
                result:
                  certificate:
                    template:
                      template: https://sunbirddev.blob.core.windows.net/sunbird-content-dev/content/test_template_stag/artifact/cbse-certificate.zip
                      identifier: template_01_pdf_stag
                      name: ''
                      params:
                      - issuer.name
                      - issuer.url
        400:
          description: BAD REQUEST. The "Read Certificate template" operation failed.
            Input for a mandatory parameter may be missing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadCertificateTemplateErrorResponse'
              example:
                id: 
                ver: 
                ts: 
                params: 
                responseCode: RESOURCE_NOT_FOUND
                result:
                  message: 'Cert template not found for the given identifier: do_213149680075849728113'
                   
                 
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong. These
            errors are tracked automatically. Try refreshing the page. If the problem
            persists, contact info@sunbird.org.
          content: 
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/500ServerError'
              example:
                id: cert.v1.template.read
                ver: v1
                ts: 1601451354559
                params: 
                  msgid: "string"
                  status: "string"
                  resmsgid: string
                responseCode: SERVER_ERROR
                result:
                  message: Process failed,please try again later.
      security:
      - bearer: []        

components:
  schemas:
    AddCertificateTemplateRequest:
      title: AddCertificateTemplateRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/AddTemplateRequest'
    AddTemplateRequest:
      title: AddTemplateRequest
      required:
      - certificate
      type: object
      properties:
        certificate:
          type: object
          properties:
            template:
              type: object
              properties:
                identifier:
                  type: string
                  description: Teh pre-defined tempalte ID
                name:
                  type: string
                  description: The name for the template
                template:
                  type: string
                  description: url for the template zip
                params:
                  type: array
                  description: The parameters attached to the template
                  items:
                    type: string
              description: The template details
          description: wrapper which holds the template details
    UpdateCertificateTemplateRequest:
      title: UpdateCertificateTemplateRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/UpdateTemplateRequest'
    UpdateTemplateRequest:
      title: UpdateTemplateRequest
      required:
      - certificate
      type: object
      properties:
        certificate:
          type: object
          properties:
            template:
              type: object
              properties:
                template:
                  type: string
                  description: url for the template zip
                params:
                  type: array
                  description: parameters attached to the template
                  items:
                    type: string
              description: template detail
          description: wrapper which holds the template details
    GetCertificateTemplateResponse:
      title: GetCertificateTemplateResponse
      required:
      - result
      type: object
      properties:
        result:
          $ref: '#/components/schemas/GetTemplateResponse'
    GetTemplateResponse:
      title: GetTemplateResponse
      type: object
      properties:
        certificate:
          type: object
          properties:
            template:
              type: object
              properties:
                name:
                  type: string
                  description: name for template
                template:
                  type: string
                  description: url for the template zip
                params:
                  type: array
                  description: parameters attached to the template
                  items:
                    type: string
              description: template details
          description: wrapper which holds the template details
    ResponseHeader:
      title: ResponseHeader
      type: object
      properties:
        id:
          type: string
          description: API Identifier
        ver:
          type: string
          description: API version information
        ts:
          type: string
          description: API execution timestamp
        params:
          $ref: '#/components/schemas/ResponseParams'
        responseCode:
          type: string
          description: 'API response code '
    ResponseParams:
      title: Response Parameter
      type: object
      properties:
        resmsgid:
          type: string
          description: Represents the response message ID
        msgid:
          type: string
          description: Represents the error message ID
        err:
          type: string
          description: Represents the error code
        status:
          type: string
          description: The response status
        errmsg:
          type: string
          description: The error message
    CreateErrorResponse:
      title: Error Response
      type: object
      properties:
        result:
          type: object
          properties:
            message:
              type: object
              description: detail of the error message
              example: name or template missing in request.
          description: Error Result
    UpdateErrorResponse:
      title: Error Response
      type: object
      properties:
        result:
          type: object
          properties:
            message:
              type: object
              description: detail of the error message
              example: 'template has invalid properties: [templateUrl]'
          description: Error Result
    ReadErrorResponse:
      title: Error Response
      type: object
      properties:
        result:
          type: object
          properties:
            message:
              type: object
              description: detail of the error message
              example: 'Cert template not found for the given identifier: template_011'
          description: Error Result
    SuccessResponse:
      type: object
      properties:
        result:
          type: object
          properties:
            identifier:
              type: string
      description: contains success response
    AddCertificateTemplateErrorResponse:
      title: Add Certificate Template Error Response
      allOf:
      - $ref: '#/components/schemas/ResponseHeader'
      - $ref: '#/components/schemas/CreateErrorResponse'
    UpdateCertificateTemplateErrorResponse:
      title: Update Certificate Template Error Response
      allOf:
      - $ref: '#/components/schemas/ResponseHeader'
      - $ref: '#/components/schemas/UpdateErrorResponse'
    ReadCertificateTemplateErrorResponse:
      title: Certificate Template Error Response
      allOf:
      - $ref: '#/components/schemas/ResponseHeader'
      - $ref: '#/components/schemas/ReadErrorResponse'
    ApiRequest:
      type: object
      properties:
        id:
          type: string
          description: Represents an API uniquely
        ver:
          type: string
          description: Represents the version of the API which was used
        ets:
          type: integer
          description: Represents the EPOCH (UTC) timestamp in milliseconds since
            EPOCH
          format: int64
        params:
          type: object
          properties:
            msgid:
              type: string
              description: Represents the unique ID of the message being sent
            did:
              type: string
              description: Represents the device UUID from which API is called
    ApiResponse:
      required:
      - ets
      - id
      - params
      - ver
      type: object
      properties:
        id:
          type: string
          description: Represents the ID of the request which was made
        ver:
          type: string
          description: Represents the version of the API which was used
        ets:
          type: integer
          description: Represents the EPOCH (UTC) timestamp in milliseconds since
            EPOCH
          format: int64
        params:
          required:
          - msgid
          - resmsgid
          - status
          type: object
          properties:
            msgid:
              type: string
              description: Represents the ID of the message sent
            resmsgid:
              type: string
              description: Represents the ID of the response message
            status:
              type: string
              enum:
              - success
              - error
        responseCode:
          type: string
    500ServerError:
      title: 500ServerError
      required:
        - id
        - ver
        - ts
        - params
        - responseCode
        - result
      type: object
      properties:
        id:
          type: string
        ver:
          type: string
        ts:
          type: string
        params:
          type: string
        responseCode:
          type: string
        result:
          type: object
          properties:
           message:
            type: string
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
    userToken:
      type: apiKey
      name: x-authenticated-user-token
      in: header
