openapi: 3.0.0
info:
  title: Program_API's
  description: 'These are the API used to do all the operations about program like creating, updating and some more operations '
  contact: {}
  version: '1.0'
servers:
- url: https://dock.sunbirded.org/content/program/v1
  variables: {}
paths:
  /list:
    post:
      tags:
      - Misc
      summary: https://dock.sunbirded.org/content/program/v1/list
      operationId: https://dock.sunbirded.org/content/program/v1/list
      parameters:
      - name: Connection
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: keep-alive
      - name: Pragma
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: no-cache
      - name: Cache-Control
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: no-cache
      - name: X-App-Id
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: dev.dock.portal
      - name: ts
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: 2020-12-02T11:25:26+05:30
      - name: X-msgid
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: e973c862-115d-51f1-5637-ca177b072a3f
      - name: User-Agent
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      - name: X-Source
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: web
      - name: X-Device-ID
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: d94997d031c714aa590c8f2380850a69
      - name: Origin
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: https://dock.sunbirded.org
      - name: Sec-Fetch-Site
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: same-origin
      - name: Sec-Fetch-Mode
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: cors
      - name: Sec-Fetch-Dest
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: empty
      - name: Referer
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: https://dock.sunbirded.org/contribute/myenrollprograms
      - name: Accept-Language
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: en-GB,en;q=0.9
      - name: Cookie
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: connect.sid=s%3A6fKZOFiFJcnIQnw998c_9Wz6Y-Aup7v4.EScUhuBdEetLBIRgsuOCAIYjc7VCtugzpqv8qCCoFoY
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/listrequest'
            example:
              request:
                filters:
                  enrolled_id:
                    user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
                  status:
                  - Live
                  - Unlisted
                sort:
                  medium:
                  - English
                  - Hindi
                  - Tamil
                  gradeLevel:
                  - Class 1
                  - Class 10
                  - Class 7
                  - Class 3
                  - Class 9
                  - Class 2
                  - Class 4
                  - Class 6
                  - Class 5
                  - Class 8
                  subject:
                  - Mathematics
                  - Hindi
                  - Science
                  - English
                  - Geography
                  - History
                  - Tamil
        required: true
      responses:
        200:
          description: ''
          headers:
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Wed, 02 Dec 2020 09:51:51 GMT
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 114522
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            X-DNS-Prefetch-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: off
            X-Frame-Options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: SAMEORIGIN
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=15552000; includeSubDomains
            X-Download-Options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: noopen
            X-Content-Type-Options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: nosniff
            X-XSS-Protection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1; mode=block
            x-ratelimit-limit-hour:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 30000
            x-ratelimit-remaining-hour:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 29992
            x-powered-by:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            access-control-allow-origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            access-control-allow-methods:
              content:
                text/plain:
                  schema:
                    type: string
                  example: GET,PUT,POST,PATCH,DELETE,OPTIONS
            access-control-allow-headers:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Content-Type, Authorization,cid, user-id, x-auth, Cache-Control, X-Requested-With, datatype, *
            etag:
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"1bf5a-UrvswHKMpx9iinf/0MZ1OXgg0HU"
            x-kong-upstream-latency:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 689
            x-kong-proxy-latency:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 0
            via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: kong/0.9.9
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Success'
              example:
                id: api.program.list
                ts: 2020-12-02T09:51:51.521Z
                params:
                  resmsgid: 0097d511-3484-11eb-9c32-15914148e3ce
                  msgid: 0097d510-3484-11eb-9c32-15914148e3ce
                  status: successful
                  err: 
                  errmsg: 
                responseCode: OK
                result:
                  programs:
                  - id: 13727
                    program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
                    user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
                    organisation_id: 
                    status: Pending
                    content_types:
                    - Asset
                    collection_ids:
                    - do_1131395604521943041440
                    feedback: 
                    rolemapping: 
                    createdby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
                    updatedby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
                    createdon: 2020-11-02T12:05:02.373Z
                    updatedon: 2020-11-02T12:05:05.722Z
                    program:
                      program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
                      name: aaa
                      type: public
                      collection_ids:
                      - do_11310770891570380814
                      - do_113108534623428608149
                      - do_113123388075057152110
                      - do_11311353404644556811
                      - do_113114880153911296165
                      - do_11312842715158937612
                      - do_113108536022335488152
                      content_types:
                      - Asset
                      target_collection_category: 
                      startdate: 2020-10-29T05:44:09.017Z
                      enddate: 2021-02-02T18:30:00Z
                      nomination_enddate: 2020-11-06T18:30:00Z
                      shortlisting_enddate: 2020-12-05T18:30:00Z
                      content_submission_enddate: 2021-01-09T18:30:00Z
                      image: 
                      status: Live
                      slug: sunbird
                      rolemapping: 
                      createdby: bf020396-0d7b-436f-ae9f-869c6780fc45
                      updatedby: 
                      createdon: 2020-10-29T05:44:09.016Z
                      updatedon: 2020-11-20T05:50:06.403Z
                      rootorg_id: 01307938306521497658
                      sourcing_org_name: Christ_University
                      channel: DIKSHA
                      template_id: template1
                      guidelines_url: 
                      subject: '["Mathematics", "Science", "Geography"]'
                      defaultContributeOrgReview: true
                      framework: ekstep_ncert_k-12
                      board: CBSE
                      gradeLevel: '["Class 1", "Class 3", "Class 9", "Class 2", "Class 7", "Class 4", "Class 6", "Class 5", "Class 10", "Class 8"]'
                      medium: '["English", "Hindi"]'
                    matchCount: 15
                  - id: 13724
                    program_id: 5d7ba0e0-18e6-11eb-81b1-659ec274e395
                    user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
                    organisation_id: 
                    status: Initiated
                    content_types:
                    - Learning Resource
                    - Explanation Content
                    - Practice Question Set
                    collection_ids: 
                    feedback: 
                    rolemapping: 
                    createdby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
                    updatedby: 
                    createdon: 2020-11-02T11:58:23.891Z
                    updatedon: 
                    program:
                      program_id: 5d7ba0e0-18e6-11eb-81b1-659ec274e395
                      name: dfgskjdhfgsakjhd
                      type: public
                      collection_ids:
                      - do_11304065892935270414
                      - do_11312349241665945618
                      - do_113133925712527360121
                      - do_113123500867362816115
                      - do_1131232640033505281322
                      - do_113123507574349824124
                      content_types:
                      - Practice Question Set
                      - Explanation Content
                      - Learning Resource
                      target_collection_category: 
                      startdate: 2020-10-28T06:25:51.571Z
                      enddate: 2020-11-07T18:30:00Z
                      nomination_enddate: 2020-11-07T18:30:00Z
                      shortlisting_enddate: 2020-11-07T18:30:00Z
                      content_submission_enddate: 2020-11-07T18:30:00Z
                      image: 
                      status: Live
                      slug: sunbird
                      rolemapping: 
                      createdby: cca53828-8111-4d71-9c45-40e569f13bad
                      updatedby: 
                      createdon: 2020-10-28T06:25:51.571Z
                      updatedon: 2020-10-28T06:25:53.886Z
                      rootorg_id: 012983850117177344161
                      sourcing_org_name: Vidya2
                      channel: DIKSHA
                      template_id: template1
                      guidelines_url: 
                      subject: '["Hindi", "Mathematics", "English"]'
                      defaultContributeOrgReview: true
                      framework: ekstep_ncert_k-12
                      board: CBSE
                      gradeLevel: '["Class 10", "Class 1", "Class 7"]'
                      medium: '["English", "Hindi"]'
                    matchCount: 8
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error-400'
              example:
                id: api.v1.list
                ver: 1.0
                ts: 2020-12-03T06:09:58.651Z
                params:
                  resmsgid: 2bead4b0-352e-11eb-86c8-875983bcd642
                  msgid: 
                  status: failed
                  err: ERR_GET_PROGRAM_DATA
                  errmsg: Required fields to get program are missing
                responseCode: CLIENT_ERROR
                result: {}
        500:
          description: Internal Server Error
      deprecated: false
components:
  schemas:
    listrequest:
      title: https://dock.sunbirded.org/content/program/v1/listrequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request'
      example:
        request:
          filters:
            enrolled_id:
              user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
            status:
            - Live
            - Unlisted
          sort:
            medium:
            - English
            - Hindi
            - Tamil
            gradeLevel:
            - Class 1
            - Class 10
            - Class 7
            - Class 3
            - Class 9
            - Class 2
            - Class 4
            - Class 6
            - Class 5
            - Class 8
            subject:
            - Mathematics
            - Hindi
            - Science
            - English
            - Geography
            - History
            - Tamil
    Request:
      title: Request
      required:
      - filters
      - sort
      type: object
      properties:
        filters:
          $ref: '#/components/schemas/Filters'
        sort:
          $ref: '#/components/schemas/Sort'
      example:
        filters:
          enrolled_id:
            user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
          status:
          - Live
          - Unlisted
        sort:
          medium:
          - English
          - Hindi
          - Tamil
          gradeLevel:
          - Class 1
          - Class 10
          - Class 7
          - Class 3
          - Class 9
          - Class 2
          - Class 4
          - Class 6
          - Class 5
          - Class 8
          subject:
          - Mathematics
          - Hindi
          - Science
          - English
          - Geography
          - History
          - Tamil
    Filters:
      title: Filters
      required:
      - enrolled_id
      - status
      type: object
      properties:
        enrolled_id:
          $ref: '#/components/schemas/EnrolledId'
        status:
          type: array
          items:
            type: string
          description: ''
      example:
        enrolled_id:
          user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
        status:
        - Live
        - Unlisted
    EnrolledId:
      title: EnrolledId
      required:
      - user_id
      type: object
      properties:
        user_id:
          type: string
      example:
        user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
    Sort:
      title: Sort
      required:
      - medium
      - gradeLevel
      - subject
      type: object
      properties:
        medium:
          type: array
          items:
            type: string
          description: ''
        gradeLevel:
          type: array
          items:
            type: string
          description: ''
        subject:
          type: array
          items:
            type: string
          description: ''
      example:
        medium:
        - English
        - Hindi
        - Tamil
        gradeLevel:
        - Class 1
        - Class 10
        - Class 7
        - Class 3
        - Class 9
        - Class 2
        - Class 4
        - Class 6
        - Class 5
        - Class 8
        subject:
        - Mathematics
        - Hindi
        - Science
        - English
        - Geography
        - History
        - Tamil
    Error-400:
      title: Error-400
      required:
      - id
      - ver
      - ts
      - params
      - responseCode
      - result
      type: object
      properties:
        id:
          type: string
        ver:
          type: string
        ts:
          type: string
        params:
          $ref: '#/components/schemas/Params'
        responseCode:
          type: string
        result:
          type: object
      example:
        id: api.v1.list
        ver: 1.0
        ts: 2020-12-03T06:09:58.651Z
        params:
          resmsgid: 2bead4b0-352e-11eb-86c8-875983bcd642
          msgid: 
          status: failed
          err: ERR_GET_PROGRAM_DATA
          errmsg: Required fields to get program are missing
        responseCode: CLIENT_ERROR
        result: {}
    Params:
      title: Params
      required:
      - resmsgid
      - msgid
      - status
      - err
      - errmsg
      type: object
      properties:
        resmsgid:
          type: string
        msgid:
          type: string
          nullable: true
        status:
          type: string
        err:
          type: string
        errmsg:
          type: string
      example:
        resmsgid: 2bead4b0-352e-11eb-86c8-875983bcd642
        msgid: 
        status: failed
        err: ERR_GET_PROGRAM_DATA
        errmsg: Required fields to get program are missing
    Success:
      title: Success
      required:
      - id
      - ts
      - params
      - responseCode
      - result
      type: object
      properties:
        id:
          type: string
        ts:
          type: string
        params:
          $ref: '#/components/schemas/Params1'
        responseCode:
          type: string
        result:
          $ref: '#/components/schemas/Result'
      example:
        id: api.program.list
        ts: 2020-12-02T09:51:51.521Z
        params:
          resmsgid: 0097d511-3484-11eb-9c32-15914148e3ce
          msgid: 0097d510-3484-11eb-9c32-15914148e3ce
          status: successful
          err: 
          errmsg: 
        responseCode: OK
        result:
          programs:
          - id: 13727
            program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
            user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
            organisation_id: 
            status: Pending
            content_types:
            - Asset
            collection_ids:
            - do_1131395604521943041440
            feedback: 
            rolemapping: 
            createdby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
            updatedby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
            createdon: 2020-11-02T12:05:02.373Z
            updatedon: 2020-11-02T12:05:05.722Z
            program:
              program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
              name: aaa
              type: public
              collection_ids:
              - do_11310770891570380814
              - do_113108534623428608149
              - do_113123388075057152110
              - do_11311353404644556811
              - do_113114880153911296165
              - do_11312842715158937612
              - do_113108536022335488152
              content_types:
              - Asset
              target_collection_category: 
              startdate: 2020-10-29T05:44:09.017Z
              enddate: 2021-02-02T18:30:00Z
              nomination_enddate: 2020-11-06T18:30:00Z
              shortlisting_enddate: 2020-12-05T18:30:00Z
              content_submission_enddate: 2021-01-09T18:30:00Z
              image: 
              status: Live
              slug: sunbird
              rolemapping: 
              createdby: bf020396-0d7b-436f-ae9f-869c6780fc45
              updatedby: 
              createdon: 2020-10-29T05:44:09.016Z
              updatedon: 2020-11-20T05:50:06.403Z
              rootorg_id: 01307938306521497658
              sourcing_org_name: Christ_University
              channel: DIKSHA
              template_id: template1
              guidelines_url: 
              subject: '["Mathematics", "Science", "Geography"]'
              defaultContributeOrgReview: true
              framework: ekstep_ncert_k-12
              board: CBSE
              gradeLevel: '["Class 1", "Class 3", "Class 9", "Class 2", "Class 7", "Class 4", "Class 6", "Class 5", "Class 10", "Class 8"]'
              medium: '["English", "Hindi"]'
            matchCount: 15
          - id: 13724
            program_id: 5d7ba0e0-18e6-11eb-81b1-659ec274e395
            user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
            organisation_id: 
            status: Initiated
            content_types:
            - Learning Resource
            - Explanation Content
            - Practice Question Set
            collection_ids: 
            feedback: 
            rolemapping: 
            createdby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
            updatedby: 
            createdon: 2020-11-02T11:58:23.891Z
            updatedon: 
            program:
              program_id: 5d7ba0e0-18e6-11eb-81b1-659ec274e395
              name: dfgskjdhfgsakjhd
              type: public
              collection_ids:
              - do_11304065892935270414
              - do_11312349241665945618
              - do_113133925712527360121
              - do_113123500867362816115
              - do_1131232640033505281322
              - do_113123507574349824124
              content_types:
              - Practice Question Set
              - Explanation Content
              - Learning Resource
              target_collection_category: 
              startdate: 2020-10-28T06:25:51.571Z
              enddate: 2020-11-07T18:30:00Z
              nomination_enddate: 2020-11-07T18:30:00Z
              shortlisting_enddate: 2020-11-07T18:30:00Z
              content_submission_enddate: 2020-11-07T18:30:00Z
              image: 
              status: Live
              slug: sunbird
              rolemapping: 
              createdby: cca53828-8111-4d71-9c45-40e569f13bad
              updatedby: 
              createdon: 2020-10-28T06:25:51.571Z
              updatedon: 2020-10-28T06:25:53.886Z
              rootorg_id: 012983850117177344161
              sourcing_org_name: Vidya2
              channel: DIKSHA
              template_id: template1
              guidelines_url: 
              subject: '["Hindi", "Mathematics", "English"]'
              defaultContributeOrgReview: true
              framework: ekstep_ncert_k-12
              board: CBSE
              gradeLevel: '["Class 10", "Class 1", "Class 7"]'
              medium: '["English", "Hindi"]'
            matchCount: 8
    Params1:
      title: Params1
      required:
      - resmsgid
      - msgid
      - status
      - err
      - errmsg
      type: object
      properties:
        resmsgid:
          type: string
        msgid:
          type: string
        status:
          type: string
        err:
          type: string
          nullable: true
        errmsg:
          type: string
          nullable: true
      example:
        resmsgid: 0097d511-3484-11eb-9c32-15914148e3ce
        msgid: 0097d510-3484-11eb-9c32-15914148e3ce
        status: successful
        err: 
        errmsg: 
    Result:
      title: Result
      required:
      - programs
      type: object
      properties:
        programs:
          type: array
          items:
            $ref: '#/components/schemas/Program'
          description: ''
      example:
        programs:
        - id: 13727
          program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
          user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
          organisation_id: 
          status: Pending
          content_types:
          - Asset
          collection_ids:
          - do_1131395604521943041440
          feedback: 
          rolemapping: 
          createdby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
          updatedby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
          createdon: 2020-11-02T12:05:02.373Z
          updatedon: 2020-11-02T12:05:05.722Z
          program:
            program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
            name: aaa
            type: public
            collection_ids:
            - do_11310770891570380814
            - do_113108534623428608149
            - do_113123388075057152110
            - do_11311353404644556811
            - do_113114880153911296165
            - do_11312842715158937612
            - do_113108536022335488152
            content_types:
            - Asset
            target_collection_category: 
            startdate: 2020-10-29T05:44:09.017Z
            enddate: 2021-02-02T18:30:00Z
            nomination_enddate: 2020-11-06T18:30:00Z
            shortlisting_enddate: 2020-12-05T18:30:00Z
            content_submission_enddate: 2021-01-09T18:30:00Z
            image: 
            status: Live
            slug: sunbird
            rolemapping: 
            createdby: bf020396-0d7b-436f-ae9f-869c6780fc45
            updatedby: 
            createdon: 2020-10-29T05:44:09.016Z
            updatedon: 2020-11-20T05:50:06.403Z
            rootorg_id: 01307938306521497658
            sourcing_org_name: Christ_University
            channel: DIKSHA
            template_id: template1
            guidelines_url: 
            subject: '["Mathematics", "Science", "Geography"]'
            defaultContributeOrgReview: true
            framework: ekstep_ncert_k-12
            board: CBSE
            gradeLevel: '["Class 1", "Class 3", "Class 9", "Class 2", "Class 7", "Class 4", "Class 6", "Class 5", "Class 10", "Class 8"]'
            medium: '["English", "Hindi"]'
          matchCount: 15
        - id: 13724
          program_id: 5d7ba0e0-18e6-11eb-81b1-659ec274e395
          user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
          organisation_id: 
          status: Initiated
          content_types:
          - Learning Resource
          - Explanation Content
          - Practice Question Set
          collection_ids: 
          feedback: 
          rolemapping: 
          createdby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
          updatedby: 
          createdon: 2020-11-02T11:58:23.891Z
          updatedon: 
          program:
            program_id: 5d7ba0e0-18e6-11eb-81b1-659ec274e395
            name: dfgskjdhfgsakjhd
            type: public
            collection_ids:
            - do_11304065892935270414
            - do_11312349241665945618
            - do_113133925712527360121
            - do_113123500867362816115
            - do_1131232640033505281322
            - do_113123507574349824124
            content_types:
            - Practice Question Set
            - Explanation Content
            - Learning Resource
            target_collection_category: 
            startdate: 2020-10-28T06:25:51.571Z
            enddate: 2020-11-07T18:30:00Z
            nomination_enddate: 2020-11-07T18:30:00Z
            shortlisting_enddate: 2020-11-07T18:30:00Z
            content_submission_enddate: 2020-11-07T18:30:00Z
            image: 
            status: Live
            slug: sunbird
            rolemapping: 
            createdby: cca53828-8111-4d71-9c45-40e569f13bad
            updatedby: 
            createdon: 2020-10-28T06:25:51.571Z
            updatedon: 2020-10-28T06:25:53.886Z
            rootorg_id: 012983850117177344161
            sourcing_org_name: Vidya2
            channel: DIKSHA
            template_id: template1
            guidelines_url: 
            subject: '["Hindi", "Mathematics", "English"]'
            defaultContributeOrgReview: true
            framework: ekstep_ncert_k-12
            board: CBSE
            gradeLevel: '["Class 10", "Class 1", "Class 7"]'
            medium: '["English", "Hindi"]'
          matchCount: 8
    Program:
      title: Program
      required:
      - id
      - program_id
      - user_id
      - organisation_id
      - status
      - content_types
      - collection_ids
      - feedback
      - rolemapping
      - createdby
      - updatedby
      - createdon
      - updatedon
      - program
      - matchCount
      type: object
      properties:
        id:
          type: integer
          format: int32
        program_id:
          type: string
        user_id:
          type: string
        organisation_id:
          type: string
          nullable: true
        status:
          type: string
        content_types:
          type: array
          items:
            type: string
          description: ''
        collection_ids:
          type: array
          items:
            type: string
          description: ''
          nullable: true
        feedback:
          type: string
          nullable: true
        rolemapping:
          type: string
          nullable: true
        createdby:
          type: string
        updatedby:
          type: string
          nullable: true
        createdon:
          type: string
        updatedon:
          type: string
          nullable: true
        program:
          $ref: '#/components/schemas/Program1'
        matchCount:
          type: integer
          format: int32
      example:
        id: 13727
        program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
        user_id: 19ba0e4e-9285-4335-8dd0-f674bf03fa4d
        organisation_id: 
        status: Pending
        content_types:
        - Asset
        collection_ids:
        - do_1131395604521943041440
        feedback: 
        rolemapping: 
        createdby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
        updatedby: bcc23eec-5290-4ca2-8f3e-144a24f03b6d
        createdon: 2020-11-02T12:05:02.373Z
        updatedon: 2020-11-02T12:05:05.722Z
        program:
          program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
          name: aaa
          type: public
          collection_ids:
          - do_11310770891570380814
          - do_113108534623428608149
          - do_113123388075057152110
          - do_11311353404644556811
          - do_113114880153911296165
          - do_11312842715158937612
          - do_113108536022335488152
          content_types:
          - Asset
          target_collection_category: 
          startdate: 2020-10-29T05:44:09.017Z
          enddate: 2021-02-02T18:30:00Z
          nomination_enddate: 2020-11-06T18:30:00Z
          shortlisting_enddate: 2020-12-05T18:30:00Z
          content_submission_enddate: 2021-01-09T18:30:00Z
          image: 
          status: Live
          slug: sunbird
          rolemapping: 
          createdby: bf020396-0d7b-436f-ae9f-869c6780fc45
          updatedby: 
          createdon: 2020-10-29T05:44:09.016Z
          updatedon: 2020-11-20T05:50:06.403Z
          rootorg_id: 01307938306521497658
          sourcing_org_name: Christ_University
          channel: DIKSHA
          template_id: template1
          guidelines_url: 
          subject: '["Mathematics", "Science", "Geography"]'
          defaultContributeOrgReview: true
          framework: ekstep_ncert_k-12
          board: CBSE
          gradeLevel: '["Class 1", "Class 3", "Class 9", "Class 2", "Class 7", "Class 4", "Class 6", "Class 5", "Class 10", "Class 8"]'
          medium: '["English", "Hindi"]'
        matchCount: 15
    Program1:
      title: Program1
      required:
      - program_id
      - name
      - type
      - collection_ids
      - content_types
      - target_collection_category
      - startdate
      - enddate
      - nomination_enddate
      - shortlisting_enddate
      - content_submission_enddate
      - image
      - status
      - slug
      - rolemapping
      - createdby
      - updatedby
      - createdon
      - updatedon
      - rootorg_id
      - sourcing_org_name
      - channel
      - template_id
      - guidelines_url
      - subject
      - defaultContributeOrgReview
      - framework
      - board
      - gradeLevel
      - medium
      type: object
      properties:
        program_id:
          type: string
        name:
          type: string
        type:
          type: string
        collection_ids:
          type: array
          items:
            type: string
          description: ''
        content_types:
          type: array
          items:
            type: string
          description: ''
        target_collection_category:
          type: array
          items:
            type: string
          description: ''
          nullable: true
        startdate:
          type: string
        enddate:
          type: string
        nomination_enddate:
          type: string
        shortlisting_enddate:
          type: string
        content_submission_enddate:
          type: string
        image:
          type: string
          nullable: true
        status:
          type: string
        slug:
          type: string
        rolemapping:
          $ref: '#/components/schemas/Rolemapping'
        createdby:
          type: string
        updatedby:
          type: string
          nullable: true
        createdon:
          type: string
        updatedon:
          type: string
        rootorg_id:
          type: string
        sourcing_org_name:
          type: string
        channel:
          type: string
        template_id:
          type: string
        guidelines_url:
          type: string
          nullable: true
        subject:
          type: string
        defaultContributeOrgReview:
          type: string
          nullable: true
        framework:
          type: string
        board:
          type: string
          nullable: true
        gradeLevel:
          type: string
        medium:
          type: string
      example:
        program_id: ba0f3ba0-19a9-11eb-81b1-659ec274e395
        name: aaa
        type: public
        collection_ids:
        - do_11310770891570380814
        - do_113108534623428608149
        - do_113123388075057152110
        - do_11311353404644556811
        - do_113114880153911296165
        - do_11312842715158937612
        - do_113108536022335488152
        content_types:
        - Asset
        target_collection_category: 
        startdate: 2020-10-29T05:44:09.017Z
        enddate: 2021-02-02T18:30:00Z
        nomination_enddate: 2020-11-06T18:30:00Z
        shortlisting_enddate: 2020-12-05T18:30:00Z
        content_submission_enddate: 2021-01-09T18:30:00Z
        image: 
        status: Live
        slug: sunbird
        rolemapping: 
        createdby: bf020396-0d7b-436f-ae9f-869c6780fc45
        updatedby: 
        createdon: 2020-10-29T05:44:09.016Z
        updatedon: 2020-11-20T05:50:06.403Z
        rootorg_id: 01307938306521497658
        sourcing_org_name: Christ_University
        channel: DIKSHA
        template_id: template1
        guidelines_url: 
        subject: '["Mathematics", "Science", "Geography"]'
        defaultContributeOrgReview: true
        framework: ekstep_ncert_k-12
        board: CBSE
        gradeLevel: '["Class 1", "Class 3", "Class 9", "Class 2", "Class 7", "Class 4", "Class 6", "Class 5", "Class 10", "Class 8"]'
        medium: '["English", "Hindi"]'
    Rolemapping:
      title: Rolemapping
      type: object
      properties:
        REVIEWER:
          type: array
          items:
            type: string
          description: ''
tags:
- name: Misc
  description: ''
